#pragma once

#define CURSOR_SENSITIVITY 0.2f
#define ZOOM_SENSITIVITY 10.0f
#define ZOOM_CTRL_SENSITIVITY 7.5f

#define TERRAIN_BASE_SIZE 512
#define TERRAIN_BASE_FREQUENCY 4.0f
#define TERRAIN_BASE_OCTAVES 6
#define TERRAIN_BASE_SEED 12345
#define TERRAIN_BASE_HEIGHTSCALE 100
